### ISSUE TITLE
Cannot get unfetched attribute [attribute] from detached object 

### ISSUE THREAD

**Issue by maslopop** [mariodavid/cuba-component-user-inbox#16] opened 2019-07-02 09:20 UTC
Opening the Entity edit screen from the Message Browse "Record", all field works fine ...
but in Message Details screen when I "click" on the Entity I get  

> IllegalStateException: Cannot get unfetched attribute [approvato] from detached object com.nuvola.workflownuvola.entity.Anomalia-d03a382d-f83d-022c-cc3d-e7b758db3544 [detached].

**Comment by mariodavid** [comment] 2020-03-21 18:31
hi,

sorry for not responding in time... Unfortunately I was not able to reproduce the problem. See attached screencast:

![2020-03-21 19 28 54](https://user-images.githubusercontent.com/817400/77233809-54d3cb00-6baa-11ea-9c8f-df58ab2b8050.gif)

From the error, it seems there is a problem with the view of your application.

If the error still persists, please provide more information. I will close the issue for now.

Cheers
Mario

**Closed by mariodavid** 2020-03-21 18:31 UTC
